"use client";

import "./globals.css";
import Header from "@/components/layout/Header";
import Aside from "@/components/layout/Aside";
import NextAuthProvider from "@/auth-provider/index";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex bg-ourBlack">
        <NextAuthProvider>
          <Aside />
          <div className="flex flex-1 flex-col ml-[calc(25vw+24px)] mr-6 my-6 sm:m-4">
            <Header />
            <main>{children}</main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
